import * as path from "path";
import * as fs from "fs";
import Database from "better-sqlite3";
import { drizzle, BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { config } from "../config";
import * as schema from "./schema";

// ---------------------------------------------------------------------------
// SQLite connection singleton
// ---------------------------------------------------------------------------

let db: BetterSQLite3Database<typeof schema> | null = null;
let sqlite: Database.Database | null = null;

/**
 * Returns the Drizzle database instance. Lazy-initialized on first call.
 * Runs migrations on first access to create/update tables.
 */
export function getDb(): BetterSQLite3Database<typeof schema> {
  if (db) return db;

  const dbPath = path.join(config.workspaceDir, "data", "workflows.db");

  // Ensure data/ directory exists
  const dir = path.dirname(dbPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  sqlite = new Database(dbPath);

  // WAL mode for concurrent reads, foreign keys enforced
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");

  db = drizzle(sqlite, { schema });

  // Run migrations — creates tables on first access, applies changes on schema updates.
  // Migration files live in drizzle/ (generated by `npx drizzle-kit generate`).
  // Dev workflow: change schema.ts → delete DB → `npx drizzle-kit generate` → restart.
  // Prod (dist/orchestrator/) → ../drizzle = dist/drizzle/ ✓ (build script copies drizzle/ into dist/)
  // Dev (src/orchestrator/)  → ../drizzle = src/drizzle/ ✗ → fall back to ../../drizzle/ (project root)
  const prodPath = path.join(import.meta.dirname, "..", "drizzle");
  const devPath = path.join(import.meta.dirname, "..", "..", "drizzle");
  const migrationsFolder = fs.existsSync(path.join(prodPath, "meta")) ? prodPath : devPath;
  migrate(db, { migrationsFolder });

  console.log(`[orchestrator] Database ready: ${dbPath}`);

  return db;
}

/**
 * Closes the database connection. Call on shutdown.
 */
export function closeDb(): void {
  if (sqlite) {
    sqlite.close();
    sqlite = null;
    db = null;
    console.log("[orchestrator] Database closed");
  }
}
